# Generated by Django 4.2.11 on 2024-06-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("basic_access", "Can access this app"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="MonthlyStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=254)),
                ("beehive", models.IntegerField()),
                ("corp", models.IntegerField()),
                ("cricket", models.IntegerField()),
                ("gsol", models.IntegerField()),
                ("incursion_hq", models.IntegerField()),
                ("incursion_vg", models.IntegerField()),
                ("locust", models.IntegerField()),
                ("peacetime", models.IntegerField()),
                ("scouts", models.IntegerField()),
                ("sig_squad", models.IntegerField()),
                ("strategic", models.IntegerField()),
                ("month", models.DateField()),
            ],
        ),
    ]
