# Generated by Django 4.2.11 on 2024-06-24 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("basic_access", "Can access this app"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CSVColumnMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=100, unique=True)),
                ("mapped_to", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IgnoredCSVColumns",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyFleetType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=10)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
            options={
                "unique_together": {("name", "source", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyUserStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                ("corporation_id", models.PositiveIntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("total_fats", models.PositiveIntegerField()),
                (
                    "fleet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lawn_stats.monthlyfleettype",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "month", "year", "fleet_type")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyCreatorStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creator_id", models.IntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("total_created", models.IntegerField(default=0)),
                (
                    "fleet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lawn_stats.monthlyfleettype",
                    ),
                ),
            ],
            options={
                "unique_together": {("creator_id", "month", "year", "fleet_type")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyCorpStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corporation_id", models.PositiveIntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("total_fats", models.PositiveIntegerField()),
                (
                    "fleet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lawn_stats.monthlyfleettype",
                    ),
                ),
            ],
            options={
                "unique_together": {("corporation_id", "month", "year", "fleet_type")},
            },
        ),
    ]
