# Generated by Django 4.2.11 on 2024-06-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lawn_stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlystats",
            name="incursion",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlystats",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="account",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="beehive",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="locust",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="month",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="peacetime",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="scouts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="sig_squad",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monthlystats",
            name="strategic",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="monthlystats",
            unique_together={("account", "year", "month")},
        ),
        migrations.RemoveField(
            model_name="monthlystats",
            name="corp",
        ),
        migrations.RemoveField(
            model_name="monthlystats",
            name="cricket",
        ),
        migrations.RemoveField(
            model_name="monthlystats",
            name="gsol",
        ),
        migrations.RemoveField(
            model_name="monthlystats",
            name="incursion_hq",
        ),
        migrations.RemoveField(
            model_name="monthlystats",
            name="incursion_vg",
        ),
    ]
